version: '3.8'

services:
  complaint-app:
    image: openjdk:21-jdk
    container_name: complaint-app
    command: ["java", "-jar", "/app/complaint-rest-api.jar", "--spring.profiles.active=prod"]
    volumes:
      - ./target/complaint-rest-api.jar:/app/complaint-rest-api.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}/${DB_NAME}?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-data:

