spring:
  flyway:
    enable: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  application:
    name: complaint-rest-api

geo-lite:
  database:
    path: geolite/GeoLite2-Country.mmdb

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

ip-api:
  url: http://ip-api.com/json/


